name: PoisonousMushroom
version: '2.1.1'
main: com.github.yj0524.Main
api-version: 1.20
commands:
  poisonousmushroom:
    permission: op
  util:
    permission: op
  update:
    permission: console
  configreload:
    permission: op
  evolve:
    permission: op
  attach:
    permission: op
  sacrifice:
    permission: not op
  getcoordinate:
    permission: op